version: "3"

services:
  app:
    image: docker.io/oliveiracooper73162/web_app:latest
    container_name: webacademydemo
    restart: always
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
