name: GCP Deploy

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
      - name: Check lint result
        if: failure()
        run: echo "Código precisa ser revisado!"

  build_docker:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          dockerfile: ./Dockerfile
          tags: docker.io/oliveiracooper73162/webacademy:latest

  deploy:
    needs: build_docker
    runs-on: ubuntu-latest
    environment: wagcp_deploy
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/webacademy:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker --quiet
      - name: Build Docker image for GCP
        run: docker build -t $IMAGE_NAME .
      - name: Push Docker image to GCP
        run: docker push $IMAGE_NAME
      - name: Deploy to Cloud Run
        run: gcloud run deploy wacicd --image $IMAGE_NAME --region us-west1 --memory 128Mi --min-instances 0 --max-instances 1 --platform managed --port 8080 --allow-unauthenticated
